#!/bin/python

def solution(mylist):

        suma=sum(mylist)
        N=len(mylist)
        izq=0

        if N == 0: return -1;

        for P in xrange(N):
                der=suma-izq-mylist[P]
                if izq == der:
                        return P
                        break;
                izq=izq+mylist[P]

        return -1

############# Example Array ############

mylist=[-7,1,5,2,-4,3,0];

var=solution(mylist);

